project:
  type: website

website:
  title: "basimol"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Examples"
        menu:
          - text: "Rapamycin"
            href: examples/Rapamycin.html

    right:
      - icon: github
        href: https://github.com/zachcp/basimol

format:
  html:
    highlight-style: github
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



